imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:          %secret%
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "@LiloApp/form.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['LiloAppBundle']
    filters:
        less:
            node:       /usr/local/bin/node
            node_paths: ['/usr/local/lib/node_modules']
            apply_to:   "\.less$"
        yui_css:
            jar:      %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        yui_js:
            jar:      %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server:  mongodb://localhost:27017
            options: {}
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


# Braincrafted Bootstrap Configuration
braincrafted_bootstrap:
    auto_configure:
        assetic: false
        twig: false
        knp_menu: false
        knp_paginator: true