parameters:
    database_name:    lilo

    mailer_transport: smtp
    mailer_host:      localhost
    mailer_user:      ~
    mailer_password:  ~

    locale:           en
    secret:           f221b0722f17f6c7fb60dc62d72c2746
