_auth_check:
    pattern: /auth/check
_auth_logout:
    pattern: /auth/logout

lilo_api:
    resource: "@LiloApiBundle/Controller"
    prefix:   /api
    type:     annotation

lilo_app:
    resource: "@LiloAppBundle/Controller"
    type:     annotation
lilo_app_admin:
    resource: "@LiloAppBundle/Controller/Admin"
    prefix:   /admin
    type:     annotation