jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Lilo\AppBundle\Document\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        mongodb:
            id: security_provider.doctrine.odm.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/auth/login$
            security: false

        api:
            pattern:  ^/api
            key:      true

        app:
            pattern:  ^/
            form_login:
                check_path:  _auth_check
                login_path:  _auth_login

                use_referer: true
            logout:
                path:        _auth_logout
                target:      _index_index

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
