jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        mongodb:
            mongodb: {class: Lilo\AppBundle\Document\User, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:  ^/foobar
            form_login:
                check_path: _authenticate
                login_path: _index_login
            logout:
                path:       _logout
                target:     _index_index
