<?php

namespace Lilo\AppBundle\Repository\Exception;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Trace
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Trace extends DocumentRepository
{
}