<?php

namespace Lilo\AppBundle\Repository;

use DateTime,
    Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Exception
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exception extends DocumentRepository
{
    public function findAllSince(DateTime $since)
    {
        return $this->createQueryBuilder()
            ->field('creationTime')->gt($since)
            ->sort('creationTime', 'DESC')
            ->getQuery()
            ->execute()
            ->toArray();
    }
}