<?php

namespace Lilo\AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Instance
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Instance extends DocumentRepository
{
}